In [ ]:
from sklearn.datasets import load_digits

In [ ]:
dt = load_digits(n_class=3)

In [ ]:
images = dt.images

In [ ]:
Y = dt.target

In [ ]:
images[-2]

array([[ 0.,  0., 15., 13.,  1.,  0.,  0.,  0.],
       [ 0.,  0., 14., 14.,  4.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  4., 12.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  6., 12.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 11., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  1., 16.,  8.,  6.,  5.,  0.],
       [ 0.,  0., 13., 16., 16., 16., 14.,  0.],
       [ 0.,  0., 10., 13., 10.,  6.,  2.,  0.]])

In [ ]:
Y[-2]

np.int64(2)

In [ ]:
images[0].reshape(1, 64)

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [ ]:
images.shape

(537, 8, 8)

In [ ]:
X = images.reshape(-1,64)

In [ ]:
X.shape

(537, 64)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [ ]:
model = nn.Sequential(
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 3),
)

In [ ]:
model(X)

tensor([[ 1.2854, -1.8503, -2.3912],
        [-0.6656, -0.7545, -0.6818],
        [-1.1095,  1.6298, -1.5275],
        ...,
        [-1.0943,  0.8392, -0.7332],
        [-0.5442,  0.7273, -0.4737],
        [ 1.3318, -1.2273, -3.3199]], grad_fn=<AddmmBackward0>)

In [ ]:
nn.NLLLoss()

NLLLoss()

In [ ]:
lossfn = nn.CrossEntropyLoss()

In [ ]:
opt = optim.Adam(model.parameters(), lr=0.01)

In [ ]:
for _ in range(30):
    opt.zero_grad()
    Yp = model(X)
    loss = lossfn(Yp, Y)
    loss.backward()
    opt.step()
    print(loss)

tensor(1.1180, grad_fn=<NllLossBackward0>)
tensor(0.8447, grad_fn=<NllLossBackward0>)
tensor(0.2803, grad_fn=<NllLossBackward0>)
tensor(0.2439, grad_fn=<NllLossBackward0>)
tensor(0.2355, grad_fn=<NllLossBackward0>)
tensor(0.1631, grad_fn=<NllLossBackward0>)
tensor(0.0999, grad_fn=<NllLossBackward0>)
tensor(0.0738, grad_fn=<NllLossBackward0>)
tensor(0.0610, grad_fn=<NllLossBackward0>)
tensor(0.0450, grad_fn=<NllLossBackward0>)
tensor(0.0310, grad_fn=<NllLossBackward0>)
tensor(0.0261, grad_fn=<NllLossBackward0>)
tensor(0.0271, grad_fn=<NllLossBackward0>)
tensor(0.0271, grad_fn=<NllLossBackward0>)
tensor(0.0236, grad_fn=<NllLossBackward0>)
tensor(0.0190, grad_fn=<NllLossBackward0>)
tensor(0.0155, grad_fn=<NllLossBackward0>)
tensor(0.0135, grad_fn=<NllLossBackward0>)
tensor(0.0126, grad_fn=<NllLossBackward0>)
tensor(0.0118, grad_fn=<NllLossBackward0>)
tensor(0.0102, grad_fn=<NllLossBackward0>)
tensor(0.0080, grad_fn=<NllLossBackward0>)
tensor(0.0063, grad_fn=<NllLossBackward0>)
tensor(0.00

In [ ]:
model(X)

tensor([[  9.4089, -12.7394,  -3.6684],
        [ -4.4829,  14.0436,   0.3094],
        [ -3.2321,   2.5141,   6.5631],
        ...,
        [ -2.9784,   0.9745,  11.3793],
        [ -1.6409,   0.1985,   6.9452],
        [  9.6333, -12.4121,  -3.0014]], grad_fn=<AddmmBackward0>)

In [ ]:
pip install opencv-python

In [ ]:
import cv2

In [ ]:
ar = cv2.imread('flower.jpg')

In [ ]:
ar.shape

(1960, 2619, 3)

In [ ]:
grar = cv2.cvtColor(ar, cv2.COLOR_BGR2GRAY)

In [ ]:
rszar = cv2.resize(grar, (8, 8))

In [ ]:
far = rszar.reshape(1, 64)

In [ ]:
far

array([[ 34,  67,  92,  95, 106,  98,  59,  41,  41,  85, 135,  80, 107,
        248, 117,  52,  51, 149,  82,  89,  41, 125,  85,  95,  59, 119,
         43,  41,  16, 234, 121, 105,  81,  81,   1,  44,  14, 118,  79,
         86, 117, 143, 141, 207,  19,  10, 175,  76,  43,  90,  27,  23,
        190,  98,  89,  49,  35, 135, 141,  46,  45,  65,  63,  35]],
      dtype=uint8)

In [ ]:
fimg = torch.FloatTensor(far)

In [ ]:
model(fimg)

tensor([[  1.7199, -74.8114, 119.7308]], grad_fn=<AddmmBackward0>)

In [ ]:
sfx = torch.softmax(model(fimg), dim=1)

In [ ]:
torch.argmax(sfx, dim=1)

tensor([2])

In [ ]:
from sklearn.datasets import load_digits
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

# 🔹 Load dataset
data = load_digits()
X = data.data          # (1797, 64)
y = data.target        # (1797,)

# 🔹 Convert to tensors
X = torch.FloatTensor(X)
y = torch.LongTensor(y)

# 🔹 Create Dataset and DataLoader (BATCHES)
dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

# 🔹 Define model
model = nn.Sequential(
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 10)   # 10 classes (0–9)
)

# 🔹 Loss function and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# 🔹 Number of epochs (more loops)
epochs = 100

# 🔹 Training loop
for epoch in range(epochs):
    total_loss = 0

    for xb, yb in loader:   # ✅ batches used here
        optimizer.zero_grad()

        output = model(xb)        # logits
        loss = loss_fn(output, yb)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss:.4f}")

# 🔹 Evaluate accuracy
correct = 0
total = 0

with torch.no_grad():
    for xb, yb in loader:
        output = model(xb)
        preds = torch.argmax(output, dim=1)

        correct += (preds == yb).sum().item()
        total += yb.size(0)

print("Accuracy:", correct / total)


Epoch 1/100, Loss: 90.4712
Epoch 2/100, Loss: 29.7213
Epoch 3/100, Loss: 17.0727
Epoch 4/100, Loss: 12.2297
Epoch 5/100, Loss: 9.7751
Epoch 6/100, Loss: 8.2800
Epoch 7/100, Loss: 6.7187
Epoch 8/100, Loss: 5.7978
Epoch 9/100, Loss: 5.1657
Epoch 10/100, Loss: 4.4367
Epoch 11/100, Loss: 3.8664
Epoch 12/100, Loss: 3.5441
Epoch 13/100, Loss: 3.3458
Epoch 14/100, Loss: 2.9773
Epoch 15/100, Loss: 2.6844
Epoch 16/100, Loss: 2.5706
Epoch 17/100, Loss: 2.1430
Epoch 18/100, Loss: 2.0839
Epoch 19/100, Loss: 1.9355
Epoch 20/100, Loss: 1.8098
Epoch 21/100, Loss: 1.6821
Epoch 22/100, Loss: 1.5689
Epoch 23/100, Loss: 1.3899
Epoch 24/100, Loss: 1.3422
Epoch 25/100, Loss: 1.1919
Epoch 26/100, Loss: 1.2689
Epoch 27/100, Loss: 1.0316
Epoch 28/100, Loss: 1.0504
Epoch 29/100, Loss: 1.0008
Epoch 30/100, Loss: 0.9492
Epoch 31/100, Loss: 0.7920
Epoch 32/100, Loss: 0.7816
Epoch 33/100, Loss: 0.7272
Epoch 34/100, Loss: 0.6774
Epoch 35/100, Loss: 0.6474
Epoch 36/100, Loss: 0.6020
Epoch 37/100, Loss: 0.5801
Epoch 

In [ ]:
from sklearn.datasets import load_digits

In [ ]:
dt = load_digits(n_class=3)

In [ ]:
images = dt.images

In [ ]:
Y = dt.target

In [ ]:
images[-2]

array([[ 0.,  0., 15., 13.,  1.,  0.,  0.,  0.],
       [ 0.,  0., 14., 14.,  4.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  4., 12.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  6., 12.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 11., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  1., 16.,  8.,  6.,  5.,  0.],
       [ 0.,  0., 13., 16., 16., 16., 14.,  0.],
       [ 0.,  0., 10., 13., 10.,  6.,  2.,  0.]])

In [ ]:
Y[-2]

np.int64(2)

In [ ]:
images[0].reshape(1, 64)

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [ ]:
images.shape

(537, 8, 8)

In [ ]:
X = images.reshape(-1,64)

In [ ]:
X.shape

(537, 64)

In [ ]:
X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
model = nn.Sequential(
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 3),
)

In [ ]:
model(X)

tensor([[-0.9969,  0.0989,  0.1419],
        [-2.6768,  0.7169, -2.2276],
        [-0.7922,  2.1930, -2.4538],
        ...,
        [-3.7464,  0.8561, -2.3120],
        [-3.4965,  0.6761, -2.6693],
        [-0.7925,  0.2274,  0.2631]], grad_fn=<AddmmBackward0>)

In [ ]:
nn.NLLLoss()

NLLLoss()

In [ ]:
lossfn = nn.CrossEntropyLoss()

In [ ]:
opt = optim.Adam(model.parameters(), lr=0.01)

In [ ]:

for _ in range(30):
    opt.zero_grad()
    Yp = model(X)
    loss = lossfn(Yp, Y)
    loss.backward()
    opt.step()
    print(loss)

tensor(1.6510, grad_fn=<NllLossBackward0>)
tensor(1.4105, grad_fn=<NllLossBackward0>)
tensor(0.8892, grad_fn=<NllLossBackward0>)
tensor(0.4669, grad_fn=<NllLossBackward0>)
tensor(0.3320, grad_fn=<NllLossBackward0>)
tensor(0.3286, grad_fn=<NllLossBackward0>)
tensor(0.3049, grad_fn=<NllLossBackward0>)
tensor(0.2352, grad_fn=<NllLossBackward0>)
tensor(0.1685, grad_fn=<NllLossBackward0>)
tensor(0.1296, grad_fn=<NllLossBackward0>)
tensor(0.1144, grad_fn=<NllLossBackward0>)
tensor(0.1073, grad_fn=<NllLossBackward0>)
tensor(0.0970, grad_fn=<NllLossBackward0>)
tensor(0.0804, grad_fn=<NllLossBackward0>)
tensor(0.0627, grad_fn=<NllLossBackward0>)
tensor(0.0499, grad_fn=<NllLossBackward0>)
tensor(0.0433, grad_fn=<NllLossBackward0>)
tensor(0.0407, grad_fn=<NllLossBackward0>)
tensor(0.0392, grad_fn=<NllLossBackward0>)
tensor(0.0364, grad_fn=<NllLossBackward0>)
tensor(0.0318, grad_fn=<NllLossBackward0>)
tensor(0.0268, grad_fn=<NllLossBackward0>)
tensor(0.0225, grad_fn=<NllLossBackward0>)
tensor(0.02

In [ ]:
model(X)

tensor([[  8.4122, -10.7970,  -3.9018],
        [-11.6557,   7.6289,  -1.9967],
        [ -7.8665,   0.0870,   1.3325],
        ...,
        [-14.1108,  -1.5304,   7.7697],
        [-10.9645,  -1.6512,   5.5658],
        [  8.5476, -10.3000,  -5.1202]], grad_fn=<AddmmBackward0>)

In [ ]:
pip install opencv-python

In [ ]:
import cv2

In [ ]:
ar = cv2.imread('one.jpg')

In [ ]:
ar.shape

(111, 167, 3)

In [ ]:
grar = cv2.cvtColor(ar, cv2.COLOR_BGR2GRAY)

In [ ]:
rszar = cv2.resize(grar, (8, 8))

In [ ]:
far = rszar.reshape(1, 64)

In [ ]:
far

array([[  5,  31,  10,  11,  14,  19,   8,   6,  15,  33, 186, 211, 175,
         38,  90,  34,  24,  87,  79,  28,  24,  59,  53,  40, 127, 158,
        100, 212,  31,  38,  35, 147, 114, 112, 100,  10, 179,  14, 240,
        148,  74, 192,  93,  21, 223,  61, 169,  76, 129,  59,  97,  84,
        137,  20,  97,  30,  36,  56, 140, 199,  18, 195, 125,  56]],
      dtype=uint8)

In [ ]:
fimg = torch.FloatTensor(far)

In [ ]:

model(fimg)

tensor([[-93.4348, -44.6856,  27.2848]], grad_fn=<AddmmBackward0>)

In [ ]:
sfx = torch.softmax(model(fimg), dim=1)


In [ ]:

torch.argmax(sfx, dim=1)

tensor([2])

In [ ]:
# 🔹 1. Imports
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.datasets import load_digits
import numpy as np
import cv2
from google.colab import files

# 🔹 2. Load dataset
data = load_digits()
X = data.data        # (1797, 64)
y = data.target      # (1797,)

# 🔹 3. Convert to tensors
X = torch.FloatTensor(X)
y = torch.LongTensor(y)

# 🔹 4. Create batches
dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

# 🔹 5. Define model
model = nn.Sequential(
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 10)
)

# 🔹 6. Loss and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# 🔹 7. Training loop (with batches)
epochs = 50

for epoch in range(epochs):
    total_loss = 0

    for xb, yb in loader:   # 🔥 batches used here
        optimizer.zero_grad()

        output = model(xb)
        loss = loss_fn(output, yb)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss:.4f}")

# 🔹 8. Create and save a sample image (digit-like)
sample = data.images[0]     # 8x8 image
sample = (sample * 16).astype("uint8")  # scale to save

cv2.imwrite("three.png", sample)

# 🔹 Show saved file in Colab
import os
print("Files:", os.listdir())

# 🔹 9. Load and preprocess image
img = cv2.imread("three.png")

grar = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
rszar = cv2.resize(grar, (8, 8), interpolation=cv2.INTER_AREA)

# Normalize like training
rszar = rszar / 16.0

# Flatten
far = rszar.reshape(1, 64)

# Convert to tensor
fimg = torch.FloatTensor(far)

# 🔹 10. Prediction
output = model(fimg)
pred = torch.argmax(output, dim=1)

print("Prediction:", pred)   # 👉 tensor([1]) (example)

# 🔹 11. Optional: download image
files.download("three.png")

Epoch 1/50, Loss: 88.3856
Epoch 2/50, Loss: 28.9211
Epoch 3/50, Loss: 16.7041
Epoch 4/50, Loss: 12.2918
Epoch 5/50, Loss: 10.0948
Epoch 6/50, Loss: 8.6526
Epoch 7/50, Loss: 7.1141
Epoch 8/50, Loss: 6.4088
Epoch 9/50, Loss: 5.5804
Epoch 10/50, Loss: 4.9716
Epoch 11/50, Loss: 4.4037
Epoch 12/50, Loss: 4.1531
Epoch 13/50, Loss: 3.6766
Epoch 14/50, Loss: 3.5526
Epoch 15/50, Loss: 3.0274
Epoch 16/50, Loss: 3.0124
Epoch 17/50, Loss: 3.0766
Epoch 18/50, Loss: 2.5438
Epoch 19/50, Loss: 2.2377
Epoch 20/50, Loss: 2.0636
Epoch 21/50, Loss: 2.0095
Epoch 22/50, Loss: 1.8361
Epoch 23/50, Loss: 1.6232
Epoch 24/50, Loss: 1.6688
Epoch 25/50, Loss: 1.4851
Epoch 26/50, Loss: 1.3482
Epoch 27/50, Loss: 1.2419
Epoch 28/50, Loss: 1.3182
Epoch 29/50, Loss: 1.1393
Epoch 30/50, Loss: 1.1789
Epoch 31/50, Loss: 1.1096
Epoch 32/50, Loss: 0.9183
Epoch 33/50, Loss: 0.8464
Epoch 34/50, Loss: 0.8870
Epoch 35/50, Loss: 0.8238
Epoch 36/50, Loss: 0.8933
Epoch 37/50, Loss: 0.7400
Epoch 38/50, Loss: 0.6697
Epoch 39/50, Los

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>